version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - static_volume:/code/static
      - ./db.sqlite3:/code/db.sqlite3
    environment:
      - DEBUG=True

volumes:
  static_volume: