# Generated by Django 5.2.4 on 2025-08-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_item_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.IntegerField(blank=True, editable=False, max_length=3, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='color_palette.png', null=True, upload_to=''),
        ),
    ]
