# Generated by Django 5.2.4 on 2025-08-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_order_alter_item_item_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.FloatField(default=0.0),
        ),
    ]
