# Generated by Django 5.2.4 on 2025-08-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_item_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_item_price',
            field=models.IntegerField(default=0),
        ),
    ]
