# Generated by Django 5.2.4 on 2025-08-01 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_cartitem_cart_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart_item_price',
        ),
    ]
