# Generated by Django 5.2.4 on 2025-08-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_order_user_alter_order_order_id_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ordered_name',
            field=models.CharField(default='a', max_length=200),
        ),
    ]
