# Generated by Django 5.2.4 on 2025-08-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_orderitem_ordered_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered_name',
        ),
    ]
