# Generated by Django 5.2.4 on 2025-08-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_order_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='profile',
        ),
    ]
